<?php

namespace Acme\TrivialWarsServerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaRepository extends EntityRepository
{
    
    public function findPreguntaById($id) {
        
        $pregunta = $this->getEntityManager()->createQueryBuilder()
                ->select("p")
                ->from("AcmeTrivialWarsServerBundle:Pregunta", "p")
                ->where("p.idPregunta = '" . $id ."'")
                ->getQuery()
                ->getArrayResult();

        return $pregunta;
    }
    
    public function findRespuestasByPregunta($id){
        
        $respuestas = $this->getEntityManager()->createQueryBuilder()
                ->select("p,rc,r1,r2")
                ->from("AcmeTrivialWarsServerBundle:Pregunta", "p")
                ->join("p.idrespuestacorrecta", "rc")
                ->join("p.idrespuestauno", "r1")
                ->join("p.idrespuestados", "r2")
                ->where("p.idPregunta='".$id."'")
                ->getQuery()
                ->getArrayResult();
        
        return $respuestas;
        
    }
    
}

