<?php

namespace Proxies\__CG__\Acme\TrivialWarsServerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partida extends \Acme\TrivialWarsServerBundle\Entity\Partida implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idPartida', 'idJugadorGanador', 'idJugadorPerdedor1', 'idJugadorPerdedor2', 'idJugadorPerdedor3', 'numeroJugadores', 'fechaPartida', 'horaComienzo', 'horaFin');
        }

        return array('__isInitialized__', 'idPartida', 'idJugadorGanador', 'idJugadorPerdedor1', 'idJugadorPerdedor2', 'idJugadorPerdedor3', 'numeroJugadores', 'fechaPartida', 'horaComienzo', 'horaFin');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Partida $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPartida()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPartida();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPartida', array());

        return parent::getIdPartida();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJugadorGanador($idJugadorGanador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJugadorGanador', array($idJugadorGanador));

        return parent::setIdJugadorGanador($idJugadorGanador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJugadorGanador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJugadorGanador', array());

        return parent::getIdJugadorGanador();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJugadorPerdedor1($idJugadorPerdedor1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJugadorPerdedor1', array($idJugadorPerdedor1));

        return parent::setIdJugadorPerdedor1($idJugadorPerdedor1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJugadorPerdedor1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJugadorPerdedor1', array());

        return parent::getIdJugadorPerdedor1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJugadorPerdedor2($idJugadorPerdedor2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJugadorPerdedor2', array($idJugadorPerdedor2));

        return parent::setIdJugadorPerdedor2($idJugadorPerdedor2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJugadorPerdedor2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJugadorPerdedor2', array());

        return parent::getIdJugadorPerdedor2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJugadorPerdedor3($idJugadorPerdedor3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJugadorPerdedor3', array($idJugadorPerdedor3));

        return parent::setIdJugadorPerdedor3($idJugadorPerdedor3);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJugadorPerdedor3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJugadorPerdedor3', array());

        return parent::getIdJugadorPerdedor3();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroJugadores($numeroJugadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroJugadores', array($numeroJugadores));

        return parent::setNumeroJugadores($numeroJugadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroJugadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroJugadores', array());

        return parent::getNumeroJugadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPartida($fechaPartida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPartida', array($fechaPartida));

        return parent::setFechaPartida($fechaPartida);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPartida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPartida', array());

        return parent::getFechaPartida();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraComienzo($horaComienzo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraComienzo', array($horaComienzo));

        return parent::setHoraComienzo($horaComienzo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraComienzo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraComienzo', array());

        return parent::getHoraComienzo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', array($horaFin));

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', array());

        return parent::getHoraFin();
    }

}
