<?php

namespace Proxies\__CG__\Acme\TrivialWarsServerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pregunta extends \Acme\TrivialWarsServerBundle\Entity\Pregunta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idPregunta', 'pregunta', 'idrespuestacorrecta', 'idrespuestauno', 'idrespuestados');
        }

        return array('__isInitialized__', 'idPregunta', 'pregunta', 'idrespuestacorrecta', 'idrespuestauno', 'idrespuestados');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pregunta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPregunta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPregunta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPregunta', array());

        return parent::getIdPregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function setPregunta($pregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPregunta', array($pregunta));

        return parent::setPregunta($pregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function getPregunta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPregunta', array());

        return parent::getPregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrespuestacorrecta($idrespuestacorrecta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrespuestacorrecta', array($idrespuestacorrecta));

        return parent::setIdrespuestacorrecta($idrespuestacorrecta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrespuestacorrecta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrespuestacorrecta', array());

        return parent::getIdrespuestacorrecta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrespuestauno($idrespuestauno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrespuestauno', array($idrespuestauno));

        return parent::setIdrespuestauno($idrespuestauno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrespuestauno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrespuestauno', array());

        return parent::getIdrespuestauno();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrespuestados($idrespuestados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrespuestados', array($idrespuestados));

        return parent::setIdrespuestados($idrespuestados);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrespuestados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrespuestados', array());

        return parent::getIdrespuestados();
    }

}
